#
# Simple config for testing.
#
---
http_host: '::'
http_port: 8893
templates: 
  - './templates'
log_level: debug
seed_file: './seed.txt'
min_wait: 12
max_wait: 15


silos:
  - name: default
    wordlist: '/usr/share/dict/words'
    corpus: './mishmash.txt'
    template: 'booleans'
    min_wait: 0
    max_wait: 100
    
    prefixes:
      - /maze
      - /otherplace
      
  - name: extra
    wordlist: '/usr/share/dict/words'
    corpus: './mishmash.txt'
    template: 'default'
     
